version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "QD-4594 "
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
