name: 'Base'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/base/*.Dockerfile'
      - '**/base/*.hcl'
  pull_request:
    paths:
      - '**/base/*.hcl'
  schedule:
    - cron: '0 0 * * 1'

jobs:
  base:
    strategy:
      fail-fast: false
      matrix:
        version: [ "next", "2024.1", "2023.3", "2023.2" ]
        group: [ "default", "more" ]
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          workdir: ${{ matrix.version }}/base
          targets: ${{ matrix.group }}
          set: |
            *.cache-from=type=gha,scope=provenance
            *.cache-to=type=gha,scope=provenance,mode=max