name: 'Lint'
on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/Dockerfile.j2'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ "2025.1", "2025.2" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dockerfiles:
              - '${{ matrix.release }}/**'
      - if: steps.changes.outputs.dockerfiles == 'true'
        run: ./dockerfiles.py ${{ matrix.release }}
      - name: Compare the expected and actual directories
        run: |
          git status
          if [ "$(git status --porcelain ${{ matrix.release }} | wc -l)" -gt "0" ]; then
              echo "Detected uncommitted changes after build. See status below:"
              git diff --ignore-space-at-eol HEAD -- ${{ matrix.release }}
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "QD-8148 Update \`${{ matrix.release }}\` Dockerfiles"
              git push
          fi
        if: steps.changes.outputs.dockerfiles == 'true'